import './globals.css'
import type {Metadata} from 'next'
import {Mulish} from 'next/font/google'
import {ReactNode} from 'react'
import Providers from '@/app/providers'
import Banner from '@/components/banner/banner'

const mulish = Mulish({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={mulish.className}>
        <Providers>{children}</Providers>
        </body>
        </html>
    )
}
