import './globals.css'
import type {Metadata} from 'next'
import {Mulish} from 'next/font/google'
import {PropsWithChildren} from 'react'
import Providers from '@/app/providers'

const mulish = Mulish({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
    return (
        <html lang="en">
        <body className={mulish.className}>
        <Providers>{props.children}</Providers>
        </body>
        </html>
    )
}
